name: CI Pipeline

on:
  push:
    branches:
      - main
      
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Depencencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev --deploy

      - name: Run unit tests
        run: |
          export T_MAX=50
          export T_MIN=10
          pipenv run test
        env:
          T_MAX: 50
          T_MIN: 10

      - name: Install dill
        run: |
          pipenv install dill

      - name: Run pylint, for static code analysis and lint
        run: |
          pipenv run lint
          
      - name: Run black, for formatting
        run: |
          pipenv run black src/ test/

      - name: Build Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t oxygen_cs-app .

      - name: Push Docker image to DockerHub
        if: github.ref == 'refs/heads/main'
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

        run: |
          echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
          docker tag oxygen_cs-app "${DOCKERHUB_USERNAME}/oxygen_cs-app:${GITHUB_SHA::8}"
          docker push "${DOCKERHUB_USERNAME}/oxygen_cs-app:${GITHUB_SHA::8}"
